SELECT
    CD_FUNC,
    NM_FUNC,
    VL_SALARIO
FROM
    LOC_FUNCIONARIO;

SELECT
    CD_PROPRIETARIO,
    NOME_PROPRIETARIO,
    TP_PROPRIETARIO,
    TELEFONE,
    NR_CPF,
    NR_CGC,
    DS_EMAIL
FROM LOC_PROPRIETARIO
ORDER BY NOME_PROPRIETARIO DESC;